
project_id = "qflmguzmticupqtnlirf"

[functions.stripe-webhook]
verify_jwt = false

[functions.verify-payment]
verify_jwt = true

[functions.purchase-credits]
verify_jwt = true

[functions.create-subscription]
verify_jwt = true

[functions.get-credit-settings]
verify_jwt = false
