
project_id = "qflmguzmticupqtnlirf"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[[db.migrations]]
name = "original"

[realtime]
enabled = true

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 604800
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true

[functions.list-users]
verify_jwt = true

[functions.fix-permission-groups-policy]
verify_jwt = true

[functions.audit-logger]
verify_jwt = false
